nelmio_api_doc:
    documentation:
        info:
            title: Symfony Books API
            description: This is a Symfony-PHP Books API
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1(?!/doc$) # Accepts routes under /api except /api/doc
