version: '3'

services:
###> doctrine/doctrine-bundle ###
  books-db:
    image: mysql:8.0.32
    restart: unless-stopped
    container_name: books-db
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database_data:/var/lib/mysql
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
